version: '3.8'

services:
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: rails_tutorial_development
  #     MYSQL_CHARSET: utf8mb4
  #     MYSQL_COLLATION: utf8mb4_unicode_ci
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   command: --default-authentication-plugin=mysql_native_password

  # web:
  #   build: .
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     - RAILS_ENV=development
  #   stdin_open: true
  #   tty: true
  redis:
    image: redis:7.2-alpine
    container_name: fire_alarm_redis
    restart: always
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data
  ai_service:
    build:
      context: ./fire-detection-ai-service 
      dockerfile: Dockerfile
    container_name: fire_ai_service
    ports:
      - "5001:5001" 
    environment:
      - PORT=5001
    restart: unless-stopped
  client:
    build:
      context: ./nuxt-client
      dockerfile: Dockerfile
    container_name: fire_alarm_client_nuxt
    ports:
      - "8080:3000" 
    volumes:
      - ./nuxt-client:/app 
      - /app/node_modules 
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:3000
volumes:
  # db_data:
  redis_data:
